S00117372_RAD302_CA/S00117372_RAD302_CA/Controllers/LegController.cs
using S00117372_RAD302_CA.DAL;
using S00117372_RAD302_CA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace S00117372_RAD302_CA.Controllers
{
    public class LegController : Controller
    {
        //
        // GET: /Leg/

        private DALITravel _repository;

        public LegController(DALITravel repository)
        {
            _repository = repository;
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.TripList = _repository.GetAllTrips().Select(t => new { id = t.ID, value = t.Name }).Distinct();

            return View();
        }

        [HttpPost]
        public ActionResult Create(Leg leg)
        {
            if (ModelState.IsValid)
            {
                _repository.AddLeg(leg);

                return RedirectToAction("Index", "Home");
            }
            return View();
        }

    }
}

S00117372_RAD302_CA/S00117372_RAD302_CA/Controllers/TripController.cs
using S00117372_RAD302_CA.DAL;
using S00117372_RAD302_CA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace S00117372_RAD302_CA.Controllers
{
    public class TripController : Controller
    {
        //
        // GET: /Trip/

        private DALITravel _repository;

        public TripController(DALITravel repository)
        {
            _repository = repository;
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Trip trip)
        {
            if (ModelState.IsValid)
            {
                trip.Viable = false;
                trip.Complete = false;

                _repository.AddTrip(trip);

                return RedirectToAction("Index", "Home");
            }
            return View();
        }

    }
}

S00117372_RAD302_CA/S00117372_RAD302_CA/Views/Trip/Create.cshtml
@model S00117372_RAD302_CA.Models.Trip
@section header {
    <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = "navbar-brand" })</li>
                    <li class="active">@Html.ActionLink("Create Trip", "Create", "Trip", null, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Create Leg", "Create", "Leg", null, new { @class = "navbar-brand" })</li>
                </ul>
    }

<div class="form-group">
                  
                    @using(Html.BeginForm()){
                    <fieldset>
                    @Html.LabelFor(model => model.Name)
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Trip Name" })

                    @Html.LabelFor(model => model.StartDate)
                    <input type="date" name="StartDate" class="form-control" />

                    @Html.LabelFor(model => model.FinishDate)
                    <input type="date" name="FinishDate" class="form-control" />

                    @Html.LabelFor(model => model.MinimumGuests)
                    @Html.TextBoxFor(model => model.MinimumGuests, new { @class = "form-control", placeholder = "Minimum Number Of Guests" })
                    </fieldset>
                    <input type="submit" class="btn btn-info" value="Create Trip" />
                    }
                </div>